using InventoryManagementAPI.Models.CoreModels;
using InventoryManagementAPI.Models.Enums;
using InventoryManagementAPI.Services;
using Microsoft.EntityFrameworkCore;

namespace InventoryManagementAPI.Tests.RepositoryTests;

// These integration tests use the real SQL Server provider because rowversion is
// generated by SQL Server. EF Core's in-memory provider cannot reproduce this
// behaviour accurately.
//
// A stale-update test deliberately loads one row through two DbContext instances:
// context A saves first and receives a new RowVersion; context B still holds the
// original value, so SQL Server updates zero rows and EF Core throws
// DbUpdateConcurrencyException. The final assertions prove the winning update
// remains stored and was not overwritten by the stale writer.
public class EntityConcurrencyTests : IClassFixture<SqlServerFixture>
{
    private readonly SqlServerFixture _fixture;

    public EntityConcurrencyTests(SqlServerFixture fixture)
    {
        _fixture = fixture;
    }

    // Category concurrency

    [Fact]
    public async Task Category_StaleUpdate_ThrowsConcurrencyExceptionAndPreservesWinningUpdate()
    {
        // Arrange
        // Create a new category and save its ID and RowVersion for later use.
        int categoryId;
        byte[] originalRowVersion;

        // Set up the initial category in the database.
        await using (var setupContext = _fixture.CreateContext())
        {
            var category = new Category
            {
                Name = $"Concurrency category {Guid.NewGuid():N}",
                Description = "Original category description",
                IsActive = true,
                Created = DateTime.UtcNow,
                Updated = DateTime.UtcNow
            };

            setupContext.Categories.Add(category);
            await setupContext.SaveChangesAsync(CancellationToken.None);

            categoryId = category.ID;
            originalRowVersion = category.RowVersion.ToArray();
        }

        try
        {
            // Create two separate contexts to simulate concurrent updates.
            await using var contextA = _fixture.CreateContext();
            await using var contextB = _fixture.CreateContext();

            // Confirm that both contexts can retrieve the same category and that their RowVersions match the original.
            var categoryA = await contextA.Categories.FindAsync([categoryId], CancellationToken.None);
            var categoryB = await contextB.Categories.FindAsync([categoryId], CancellationToken.None);

            Assert.NotNull(categoryA);
            Assert.NotNull(categoryB);
            Assert.NotEmpty(originalRowVersion);
            Assert.Equal(originalRowVersion, categoryA.RowVersion);
            Assert.Equal(originalRowVersion, categoryB.RowVersion);

            // Update the category in contextA and save changes, which will update the RowVersion.
            categoryA.Description = "Winning category description";
            await contextA.SaveChangesAsync(CancellationToken.None);

            // Attempt to update the category in contextB, which has a stale RowVersion, and expect a concurrency exception.
            categoryB.Description = "Stale category description";
            await Assert.ThrowsAsync<DbUpdateConcurrencyException>(
                () => contextB.SaveChangesAsync(CancellationToken.None));

            // Create a new context to verify the final state of the category in the database.
            await using var verifyContext = _fixture.CreateContext();

            // store the category from the database and check that it has the winning description and a new RowVersion.
            var storedCategory = await verifyContext.Categories
                .AsNoTracking() // AsNoTracking is used here to ensure we get the latest state from the database without tracking it in the context.
                .SingleAsync(category => category.ID == categoryId); // SingleAsync is used to retrieve a single category by its ID, and it will throw an exception if no category or more than one category is found.

            //Confirm that the stored category has the winning description and a new RowVersion that is different from the original.
            Assert.Equal("Winning category description", storedCategory.Description);
            Assert.Equal(categoryA.RowVersion, storedCategory.RowVersion);
            Assert.NotEqual(originalRowVersion, storedCategory.RowVersion);
        }
        finally
        {
            // Cleanup belongs in finally so a failed assertion cannot leave data
            // behind for later integration tests.
            await DeleteCategoryAsync(categoryId);
        }
    }

    [Fact]
    public async Task Supplier_StaleUpdate_ThrowsConcurrencyExceptionAndPreservesWinningUpdate()
    {
        // Arrange: insert one supplier and retain the database-generated token.
        int supplierId;
        byte[] originalRowVersion;

        await using (var setupContext = _fixture.CreateContext())
        {
            var supplier = new Supplier
            {
                Name = $"Concurrency supplier {Guid.NewGuid():N}",
                TaxNumber = "ORIGINAL-TAX",
                Website = "https://original.example.com",
                IsActive = true,
                Created = DateTime.UtcNow,
                Updated = DateTime.UtcNow
            };

            setupContext.Suppliers.Add(supplier);
            await setupContext.SaveChangesAsync(CancellationToken.None);

            supplierId = supplier.ID;
            originalRowVersion = supplier.RowVersion.ToArray();
        }

        try
        {
            // Two contexts represent two independent requests that read the same row.
            await using var contextA = _fixture.CreateContext();
            await using var contextB = _fixture.CreateContext();

            var supplierA = await contextA.Suppliers.FindAsync([supplierId], CancellationToken.None);
            var supplierB = await contextB.Suppliers.FindAsync([supplierId], CancellationToken.None);

            Assert.NotNull(supplierA);
            Assert.NotNull(supplierB);
            Assert.NotEmpty(originalRowVersion);
            Assert.Equal(originalRowVersion, supplierA.RowVersion);
            Assert.Equal(originalRowVersion, supplierB.RowVersion);

            // Act: request A wins; request B then attempts to save its stale copy.
            supplierA.Website = "https://winner.example.com";
            await contextA.SaveChangesAsync(CancellationToken.None);

            supplierB.Website = "https://stale.example.com";
            await Assert.ThrowsAsync<DbUpdateConcurrencyException>(
                () => contextB.SaveChangesAsync(CancellationToken.None));

            // Assert: a fresh context confirms request B did not overwrite request A.
            await using var verifyContext = _fixture.CreateContext();
            var storedSupplier = await verifyContext.Suppliers
                .AsNoTracking()
                .SingleAsync(supplier => supplier.ID == supplierId);

            Assert.Equal("https://winner.example.com", storedSupplier.Website);
            Assert.Equal(supplierA.RowVersion, storedSupplier.RowVersion);
            Assert.NotEqual(originalRowVersion, storedSupplier.RowVersion);
        }
        finally
        {
            await DeleteSupplierAsync(supplierId);
        }
    }

    [Fact]
    public async Task User_StaleUpdate_ThrowsConcurrencyExceptionAndPreservesWinningUpdate()
    {
        // Arrange: persist a user and capture the initial SQL Server rowversion.
        int userId;
        byte[] originalRowVersion;

        await using (var setupContext = _fixture.CreateContext())
        {
            var user = new User
            {
                UserName = $"ConcurrencyUser{Guid.NewGuid():N}"[..30],
                Email = $"{Guid.NewGuid():N}@example.com",
                Password_Hash = BCrypt.Net.BCrypt.EnhancedHashPassword("Password1!"),
                IsActive = true,
                Created = DateTime.UtcNow,
                Updated = DateTime.UtcNow,
                LastLogin = DateTime.UtcNow
            };

            setupContext.Users.Add(user);
            await setupContext.SaveChangesAsync(CancellationToken.None);

            userId = user.ID;
            originalRowVersion = user.RowVersion.ToArray();
        }

        try
        {
            // Load separate tracked copies, just as two concurrent API requests would.
            await using var contextA = _fixture.CreateContext();
            await using var contextB = _fixture.CreateContext();

            var userA = await contextA.Users.FindAsync([userId], CancellationToken.None);
            var userB = await contextB.Users.FindAsync([userId], CancellationToken.None);

            Assert.NotNull(userA);
            Assert.NotNull(userB);
            Assert.NotEmpty(originalRowVersion);
            Assert.Equal(originalRowVersion, userA.RowVersion);
            Assert.Equal(originalRowVersion, userB.RowVersion);

            // Act: the first save changes the database token; the second must fail.
            userA.UserName = "WinningUserName";
            await contextA.SaveChangesAsync(CancellationToken.None);

            userB.UserName = "StaleUserName";
            await Assert.ThrowsAsync<DbUpdateConcurrencyException>(
                () => contextB.SaveChangesAsync(CancellationToken.None));

            // Assert against a fresh, untracked read of the database state.
            await using var verifyContext = _fixture.CreateContext();
            var storedUser = await verifyContext.Users
                .AsNoTracking()
                .SingleAsync(user => user.ID == userId);

            Assert.Equal("WinningUserName", storedUser.UserName);
            Assert.Equal(userA.RowVersion, storedUser.RowVersion);
            Assert.NotEqual(originalRowVersion, storedUser.RowVersion);
        }
        finally
        {
            await DeleteUserAsync(userId);
        }
    }

    // Product concurrency

    [Fact]
    public async Task Product_Update_GeneratesDifferentRowVersion()
    {
        // Arrange: a transaction keeps this single-context test isolated and
        // rolls back the product plus its required category and supplier.
        await using var context = _fixture.CreateContext();
        await using var transaction = await context.Database.BeginTransactionAsync(CancellationToken.None);
        var product = await CreateProductAsync(context);
        await context.SaveChangesAsync(CancellationToken.None);
        var originalRowVersion = product.RowVersion.ToArray();

        // Act: changing any persisted field causes SQL Server to issue a new token.
        product.Name = $"Updated product {Guid.NewGuid():N}";
        await context.SaveChangesAsync(CancellationToken.None);
        var updatedRowVersion = product.RowVersion.ToArray();

        // Assert: both tokens are populated and the update replaced the old one.
        Assert.NotEmpty(originalRowVersion);
        Assert.NotEmpty(updatedRowVersion);
        Assert.NotEqual(originalRowVersion, updatedRowVersion);

        await transaction.RollbackAsync(CancellationToken.None);
    }

    [Fact]
    public async Task Product_StaleUpdate_ThrowsConcurrencyExceptionAndPreservesWinningUpdate()
    {
        // Arrange: create a product, then load independent copies through two
        // contexts so both begin with the same RowVersion.
        int productId;
        await using (var setupContext = _fixture.CreateContext())
        {
            var product = await CreateProductAsync(setupContext);
            await setupContext.SaveChangesAsync(CancellationToken.None);
            productId = product.ID;
        }

        try
        {
            await using var contextA = _fixture.CreateContext();
            await using var contextB = _fixture.CreateContext();
            var productA = await contextA.Products.FindAsync([productId], CancellationToken.None);
            var productB = await contextB.Products.FindAsync([productId], CancellationToken.None);

            Assert.NotNull(productA);
            Assert.NotNull(productB);
            var originalRowVersion = productA.RowVersion.ToArray();
            Assert.NotEmpty(originalRowVersion);
            Assert.Equal(originalRowVersion, productB.RowVersion);

            // Act: context A wins and receives a new token. Context B still sends
            // the original token and EF Core surfaces the rejected update.
            productA.Name = "Winning product name";
            await contextA.SaveChangesAsync(CancellationToken.None);

            productB.Name = "Stale product name";
            await Assert.ThrowsAsync<DbUpdateConcurrencyException>(
                () => contextB.SaveChangesAsync(CancellationToken.None));

            // Assert: read through a third context to avoid either request's cache.
            await using var verifyContext = _fixture.CreateContext();
            var storedProduct = await verifyContext.Products
                .AsNoTracking()
                .SingleAsync(product => product.ID == productId);

            Assert.Equal("Winning product name", storedProduct.Name);
            Assert.Equal(productA.RowVersion, storedProduct.RowVersion);
            Assert.NotEqual(originalRowVersion, storedProduct.RowVersion);
        }
        finally
        {
            // This test commits its winning update, so explicitly remove all data
            // created for it to keep later repository tests independent.
            await DeleteProductGraphAsync(productId);
        }
    }

    private async Task<Product> CreateProductAsync(InvManDBContext context)
    {
        var category = new Category
        {
            Name = $"Concurrency category {Guid.NewGuid():N}",
            Description = "Category created for a product concurrency test"
        };
        context.Categories.Add(category);
        await context.SaveChangesAsync(CancellationToken.None);

        var product = new Product
        {
            Name = $"Concurrency product {Guid.NewGuid():N}",
            Sku = $"SKU{Guid.NewGuid():N}"[..8],
            Description = "Product created for a concurrency test",
            CategoryID = category.ID,
            Price = 9.99m,
            IsActive = true
        };
        context.Products.Add(product);
        return product;
    }

    private async Task DeleteProductGraphAsync(int productId)
    {
        await using var cleanupContext = _fixture.CreateContext();
        var product = await cleanupContext.Products.FindAsync([productId], CancellationToken.None);
        if (product == null) return;

        var category = await cleanupContext.Categories.FindAsync([product.CategoryID], CancellationToken.None);
        cleanupContext.Products.Remove(product);
        if (category != null) cleanupContext.Categories.Remove(category);
        await cleanupContext.SaveChangesAsync(CancellationToken.None);
    }

    private async Task DeleteCategoryAsync(int categoryId)
    {
        await using var cleanupContext = _fixture.CreateContext();
        var category = await cleanupContext.Categories.FindAsync([categoryId], CancellationToken.None);
        if (category == null) return;

        cleanupContext.Categories.Remove(category);
        await cleanupContext.SaveChangesAsync(CancellationToken.None);
    }

    private async Task DeleteSupplierAsync(int supplierId)
    {
        await using var cleanupContext = _fixture.CreateContext();
        var supplier = await cleanupContext.Suppliers.FindAsync([supplierId], CancellationToken.None);
        if (supplier == null) return;

        cleanupContext.Suppliers.Remove(supplier);
        await cleanupContext.SaveChangesAsync(CancellationToken.None);
    }

    private async Task DeleteUserAsync(int userId)
    {
        await using var cleanupContext = _fixture.CreateContext();
        var user = await cleanupContext.Users.FindAsync([userId], CancellationToken.None);
        if (user == null) return;

        cleanupContext.Users.Remove(user);
        await cleanupContext.SaveChangesAsync(CancellationToken.None);
    }
}
