// <auto-generated />
using System;
using InventoryManagementAPI.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryManagementAPI.Migrations
{
    [DbContext(typeof(InvManDBContext))]
    partial class InvManDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryManagementAPI.Models.CoreModels.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateOnly>("Created")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Updated")
                        .HasColumnType("date");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Created = new DateOnly(2026, 4, 17),
                            Description = "Things that are cool",
                            IsActive = true,
                            Name = "CoolStuff",
                            Updated = new DateOnly(2026, 4, 17)
                        },
                        new
                        {
                            ID = 2,
                            Created = new DateOnly(2026, 4, 17),
                            Description = "Things that are cooler",
                            IsActive = true,
                            Name = "CoolerStuff",
                            Updated = new DateOnly(2026, 4, 17)
                        },
                        new
                        {
                            ID = 3,
                            Created = new DateOnly(2026, 4, 17),
                            Description = "Things that are coolest",
                            IsActive = true,
                            Name = "CoolestStuff",
                            Updated = new DateOnly(2026, 4, 17)
                        });
                });

            modelBuilder.Entity("InventoryManagementAPI.Models.CoreModels.InventoryMovement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserID");

                    b.ToTable("InventoryMovements");
                });

            modelBuilder.Entity("InventoryManagementAPI.Models.CoreModels.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("SupplierID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 1,
                            Created = new DateOnly(1, 1, 1),
                            Description = "Test",
                            IsActive = true,
                            Name = "Test",
                            Price = 123m,
                            QuantityInStock = 420,
                            ReorderLevel = 69,
                            Sku = "Test",
                            SupplierID = 1,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 1,
                            Created = new DateOnly(1, 1, 1),
                            Description = "Test2",
                            IsActive = true,
                            Name = "Test2",
                            Price = 123.85m,
                            QuantityInStock = 420,
                            ReorderLevel = 69,
                            Sku = "Test2",
                            SupplierID = 2,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 2,
                            Created = new DateOnly(1, 1, 1),
                            Description = "Test3",
                            IsActive = true,
                            Name = "Test3",
                            Price = 123.85m,
                            QuantityInStock = 420,
                            ReorderLevel = 69,
                            Sku = "Test3",
                            SupplierID = 2,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("InventoryManagementAPI.Models.CoreModels.Supplier", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "TestSupplier",
                            ContactName = "TestSupplier",
                            EmailContact = "TestSupplier",
                            IsActive = true,
                            Name = "TestSupplier",
                            PhoneContact = "TestSupplier"
                        },
                        new
                        {
                            ID = 2,
                            Address = "TestSupplier",
                            ContactName = "TestSupplier",
                            EmailContact = "TestSupplier",
                            IsActive = true,
                            Name = "TestSupplier",
                            PhoneContact = "TestSupplier"
                        },
                        new
                        {
                            ID = 3,
                            Address = "TestSupplier",
                            ContactName = "TestSupplier",
                            EmailContact = "TestSupplier",
                            IsActive = true,
                            Name = "TestSupplier",
                            PhoneContact = "TestSupplier"
                        });
                });

            modelBuilder.Entity("InventoryManagementAPI.Models.CoreModels.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateOnly>("Created")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password_Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InventoryManagementAPI.Models.CoreModels.InventoryMovement", b =>
                {
                    b.HasOne("InventoryManagementAPI.Models.CoreModels.Product", "Product")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagementAPI.Models.CoreModels.User", "User")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InventoryManagementAPI.Models.CoreModels.Product", b =>
                {
                    b.HasOne("InventoryManagementAPI.Models.CoreModels.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagementAPI.Models.CoreModels.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("InventoryManagementAPI.Models.CoreModels.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("InventoryManagementAPI.Models.CoreModels.Product", b =>
                {
                    b.Navigation("InventoryMovements");
                });

            modelBuilder.Entity("InventoryManagementAPI.Models.CoreModels.Supplier", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("InventoryManagementAPI.Models.CoreModels.User", b =>
                {
                    b.Navigation("InventoryMovements");
                });
#pragma warning restore 612, 618
        }
    }
}
